version: "3.0"
services:
  speedtest-exporter:
    image: miguelndecarvalho/speedtest-exporter
    restart: unless-stopped
    container_name: speedtest-exporter
    # environment:
    #   - SPEEDTEST_PORT=<speedtest-port> #optional
    #   - SPEEDTEST_SERVER=<server-id> #optional
    ports:
      - 9798:9798
  prom:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"